/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;
import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.bean.Servico;
import model.dao.ServicoDAO;
import javax.swing.JOptionPane; // Para exibir mensagens de diálogo

/**
 *
 * @author Aluno
 */
public class PainelTabelaServicos extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaFornecedor
     */
    public PainelTabelaServicos() {
        initComponents();
        DefaultTableModel dtm = new DefaultTableModel();
        dtm.addColumn("id");
        dtm.addColumn("nome");
        dtm.addColumn("descricao");
        dtm.addColumn("preco");
        dtm.addColumn("funcionariosId");

        servicosTable.setModel(dtm);
        
        preencherTabela(); // Preenche a tabela na inicialização
    }
    
    
     public void preencherTabela() {
        DefaultTableModel dtm = (DefaultTableModel) servicosTable.getModel();
        dtm.setRowCount(0); // Limpa a tabela antes de adicionar os novos dados
        
         ServicoDAO dao = new ServicoDAO();
        List<Servico> servicos = dao.listarServicos(); // Retorna a lista de serviços do banco
        
        for (Servico servico : servicos) {
            dtm.addRow(new Object[] {
                servico.getId(),
                servico.getNome(),
                servico.getDescricao(),
                servico.getPreco(),
                servico.getFuncionariosId()
                
            });
        }
    }

    
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        servicosTable = new javax.swing.JTable();
        editarServicoButton = new javax.swing.JButton();
        excluirServicoButton = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setClosable(true);
        setIconifiable(true);
        setTitle("Gerenciamento Serviços");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 244, Short.MAX_VALUE)
        );

        servicosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Descrição", "Preço", "Nome"
            }
        ));
        jScrollPane3.setViewportView(servicosTable);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 21, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        editarServicoButton.setText("Editar");
        editarServicoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarServicoButtonActionPerformed(evt);
            }
        });

        excluirServicoButton.setText("Excluir");
        excluirServicoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirServicoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(editarServicoButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(excluirServicoButton)
                        .addGap(103, 103, 103))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editarServicoButton)
                    .addComponent(excluirServicoButton))
                .addGap(51, 51, 51))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editarServicoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarServicoButtonActionPerformed
   // Recuperar a linha selecionada na tabela
    int selectedRow = servicosTable.getSelectedRow();
    if (selectedRow != -1) {
        // Obtém os dados da linha selecionada
        int idServico = (int) servicosTable.getValueAt(selectedRow, 0); // ID
        String nomeServico = (String) servicosTable.getValueAt(selectedRow, 1); // Nome
        String descricaoServico = (String) servicosTable.getValueAt(selectedRow, 2); // Descrição
        double precoServico = (double) servicosTable.getValueAt(selectedRow, 3); // Preço4
        int funcionariosId  = (int) servicosTable.getValueAt(selectedRow, 4); // Preço4


        // Exibe caixas de diálogo para editar os dados
        String novoNomeServico = JOptionPane.showInputDialog(this, "Editar Nome:", nomeServico);
        String novaDescricao = JOptionPane.showInputDialog(this, "Editar descrição:", descricaoServico);
        String novoPreco = JOptionPane.showInputDialog(this, "Editar preço:", precoServico);
        String novofuncionariosId = JOptionPane.showInputDialog(this, "Editar funcionario:", funcionariosId);

        // Verifica se os dados foram preenchidos
        if (novaDescricao != null && novoPreco != null && novoNomeServico != null && novofuncionariosId != null) {
            try {
                double preco = Double.parseDouble(novoPreco); // Converte o preço para Double
                int funcionario = Integer.parseInt(novofuncionariosId);
                // Cria um objeto Servico com os novos valores
                Servico servicoEditado = new Servico(idServico, novoNomeServico, novaDescricao, preco, funcionario);
                ServicoDAO dao = new ServicoDAO();

                // Atualiza no banco de dados
                boolean sucesso = dao.editarServico(servicoEditado);
                if (sucesso) {
                    preencherTabela(); // Atualiza a tabela
                    JOptionPane.showMessageDialog(this, "Serviço atualizado com sucesso!");
                } else {
                    JOptionPane.showMessageDialog(this, "Erro ao atualizar o serviço.");
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Erro ao converter preço.");
            }
        }
    } else {
        JOptionPane.showMessageDialog(this, "Selecione um serviço para editar.");
    }

    }//GEN-LAST:event_editarServicoButtonActionPerformed

    private void excluirServicoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirServicoButtonActionPerformed
// Supondo que você tenha uma tabela para selecionar o serviço a ser excluído
int selectedRow = servicosTable.getSelectedRow();
if (selectedRow == -1) {
    JOptionPane.showMessageDialog(this, "Selecione um serviço para excluir.", "Aviso", JOptionPane.WARNING_MESSAGE);
    return;
}

// Obtendo os dados do serviço selecionado
int id = (int) servicosTable.getValueAt(selectedRow, 0); // ID
String nomeServico = (String) servicosTable.getValueAt(selectedRow, 1); // Nome

// Confirmando a exclusão
int confirm = JOptionPane.showConfirmDialog(this, 
    "Tem certeza que deseja excluir o serviço: " + nomeServico + "?", 
    "Confirmação", 
    JOptionPane.YES_NO_OPTION);
if (confirm != JOptionPane.YES_OPTION) {
    return;
}

// Excluindo o serviço do banco
ServicoDAO servicoDAO = new ServicoDAO();
boolean sucesso = false;

sucesso = servicoDAO.excluirServico(id);

if (sucesso) {
    JOptionPane.showMessageDialog(this, "Serviço " + nomeServico + " excluído com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
    preencherTabela(); // Atualiza a tabela de serviços
} else {
    JOptionPane.showMessageDialog(this, "Erro ao excluir o serviço.", "Erro", JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_excluirServicoButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton editarServicoButton;
    private javax.swing.JButton excluirServicoButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable servicosTable;
    // End of variables declaration//GEN-END:variables
}
