/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.bean.Cliente;
import model.bean.Funcionario;
import model.dao.ClienteDAO;
import model.dao.FuncionarioDAO;



/**
 *
 * @author Aluno
 */
public class PainelTabelaFuncionarios extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaFornecedor
     */
    public PainelTabelaFuncionarios() {
        initComponents();
        preencherTabela();

    }
    
     public void preencherTabela() {
        DefaultTableModel dtm = (DefaultTableModel) funcionarioTable.getModel();
        dtm.setRowCount(0);
         FuncionarioDAO dao = new FuncionarioDAO();
        
            for(Funcionario f : dao.listarFuncionarios()) {
            dtm.addRow(new Object[] {
                f.getId(),
                f.getNome(),
                f.getCargo(),
                f.getTelefone(),
                f.getEmail(),
                f.getSalario()
            });
        }
    }
    

    
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        excluirButton = new javax.swing.JButton();
        editarButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        funcionarioTable = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Gerenciamento Funcionarios");

        excluirButton.setText("Excluir");
        excluirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirButtonActionPerformed(evt);
            }
        });

        editarButton.setText("Editar");
        editarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarButtonActionPerformed(evt);
            }
        });

        funcionarioTable.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        funcionarioTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nome", "Cargo", "Telefone", "Email", "Salario"
            }
        ));
        jScrollPane2.setViewportView(funcionarioTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(editarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(excluirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editarButton)
                    .addComponent(excluirButton))
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void excluirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirButtonActionPerformed
        int selectedRow = funcionarioTable.getSelectedRow();
    if (selectedRow != -1) {
        try {
            // Obtém o ID do funcionário selecionado
            int FuncionarioID = Integer.parseInt(funcionarioTable.getValueAt(selectedRow, 0).toString());
            FuncionarioDAO dao = new FuncionarioDAO();

            // Chama o método para excluir o funcionário
            boolean sucesso = dao.excluirFuncionario(FuncionarioID);

            // Verifica o resultado da operação
            if (sucesso) {
                preencherTabela(); // Atualiza a tabela após exclusão
                JOptionPane.showMessageDialog(this, "Funcionário excluído com sucesso!");
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao excluir funcionário.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
            e.printStackTrace();
        }
    } else {
        JOptionPane.showMessageDialog(this, "Selecione um funcionário para excluir.");
    }
 
    }//GEN-LAST:event_excluirButtonActionPerformed

    private void editarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarButtonActionPerformed
        int selectedRow = funcionarioTable.getSelectedRow();
        if (selectedRow != -1) {
            int FuncionarioID = (int) funcionarioTable.getValueAt(selectedRow, 0);
            String nomeAtual = (String) funcionarioTable.getValueAt(selectedRow, 1);
            String cargoAtual = (String) funcionarioTable.getValueAt(selectedRow, 2);
            String telefoneAtual = (String) funcionarioTable.getValueAt(selectedRow, 3);
            String emailAtual = (String) funcionarioTable.getValueAt(selectedRow, 4);
            Double salarioAtual = (Double) funcionarioTable.getValueAt(selectedRow, 5);

        String nome = JOptionPane.showInputDialog(this , "Digite o nome do Funcionario:", nomeAtual);
        String cargo = JOptionPane.showInputDialog(this, "Digite o Cargo do Funcionario:", cargoAtual);
        String telefone = JOptionPane.showInputDialog(this, "Digite o telefone do Funcionario:", telefoneAtual);
        String email = JOptionPane.showInputDialog(this, "Digite o email do Funcionario:", emailAtual);
        String salario = JOptionPane.showInputDialog(this, "Digite o Salario do Funcionario:", salarioAtual);

        if (nome != null && cargo != null && telefone != null && email != null && salario != null) {
            
            
           Double salario1 = Double.parseDouble(salario);
           
            Funcionario novoFuncionario = new Funcionario(FuncionarioID, nome, cargo, telefone, email, salario1);
            FuncionarioDAO dao = new FuncionarioDAO();
            boolean sucesso = dao.atualizarFuncionario(novoFuncionario); // Método para adicionar no banco
                if (sucesso) {
                    preencherTabela();
                    JOptionPane.showMessageDialog(this, "Funcionario atualizado com sucesso!");
                } else {
                    JOptionPane.showMessageDialog(this, "Erro ao atualizar Funcionario.");
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um Funcionario para editar.");
        }
        preencherTabela();
    }//GEN-LAST:event_editarButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton editarButton;
    private javax.swing.JButton excluirButton;
    private javax.swing.JTable funcionarioTable;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
