/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;
import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import model.bean.Estoque;
import model.dao.EstoqueDAO;


/**
 *
 * @author Aluno
 */
public class PainelTabelaEstoque extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaFornecedor
     */
    public PainelTabelaEstoque() {
        initComponents();
        preencherTabela();
        

       

    }
    
     public void preencherTabela() {
         DefaultTableModel dtm = (DefaultTableModel) estoqueTable.getModel();
        dtm.setRowCount(0);
        EstoqueDAO dao = new EstoqueDAO();
        
        for(Estoque f : dao.listarProdutos()) {
            dtm.addRow(new Object[] {
                f.getId(),
                f.getNomeProduto(),
                f.getQuantidade(),
                f.getPreco(),
            });
        }
    }
    

    
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        excluirProdutoButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        estoqueTable = new javax.swing.JTable();
        editarProdutoButton = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Gerenciamento Estoque");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista Estoque", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12), new java.awt.Color(255, 51, 51))); // NOI18N

        excluirProdutoButton.setText("Excluir");
        excluirProdutoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirProdutoButtonActionPerformed(evt);
            }
        });

        estoqueTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Nome", "Qtdd", "Preço"
            }
        ));
        jScrollPane2.setViewportView(estoqueTable);

        editarProdutoButton.setText("Editar");
        editarProdutoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarProdutoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(editarProdutoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(excluirProdutoButton)
                .addGap(84, 84, 84))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(excluirProdutoButton)
                    .addComponent(editarProdutoButton))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void excluirProdutoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirProdutoButtonActionPerformed
     int selectedRow = estoqueTable.getSelectedRow();
        if (selectedRow != -1) {
            int clienteId = (int) estoqueTable.getValueAt(selectedRow, 0);
            EstoqueDAO dao = new EstoqueDAO();
            boolean sucesso = dao.excluirProduto(clienteId); // Chama o método modificado
            if (sucesso) {
                preencherTabela(); // Atualiza a tabela após a exclusão
                JOptionPane.showMessageDialog(this, "Produto excluído com sucesso!");
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao excluir produto.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um Produto para excluir.");
        }
        preencherTabela();
    }//GEN-LAST:event_excluirProdutoButtonActionPerformed

    private void editarProdutoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarProdutoButtonActionPerformed
    // Recuperar a linha selecionada na tabela
int selectedRow = estoqueTable.getSelectedRow();
if (selectedRow != -1) {
    int idProduto = (int) estoqueTable.getValueAt(selectedRow, 0); // ID do produto
    String nomeProduto = (String) estoqueTable.getValueAt(selectedRow, 1); // Nome do produto
    int quantidadeProduto = (int) estoqueTable.getValueAt(selectedRow, 2); // Quantidade (verifique se é Integer)
    double precoProduto = (double) estoqueTable.getValueAt(selectedRow, 3); // Preço (verifique se é Double)
    
    // Agora você pode editar os dados
    String novoNome = JOptionPane.showInputDialog(this, "Editar nome:", nomeProduto);
    String novaQuantidade = JOptionPane.showInputDialog(this, "Editar quantidade:", quantidadeProduto);
    String novoPreco = JOptionPane.showInputDialog(this, "Editar preço:", precoProduto);
    
    // A seguir, você deve garantir que os dados recuperados sejam corretamente convertidos para os tipos esperados.
    if (novoNome != null && novaQuantidade != null && novoPreco != null) {
        try {
            int quantidade = Integer.parseInt(novaQuantidade); // Converte a quantidade para Integer
            double preco = Double.parseDouble(novoPreco); // Converte o preço para Double
            
            Estoque produtoEditado = new Estoque(idProduto, novoNome, preco, quantidade);
            EstoqueDAO dao = new EstoqueDAO();
            boolean sucesso = dao.editarProduto(produtoEditado);
            if (sucesso) {
                preencherTabela();
                JOptionPane.showMessageDialog(this, "Estoque atualizado com sucesso!");
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao atualizar o estoque.");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Erro ao converter quantidade ou preço.");
        }
    }
} else {
    JOptionPane.showMessageDialog(this, "Selecione um produto para editar.");
}


    }//GEN-LAST:event_editarProdutoButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton editarProdutoButton;
    private javax.swing.JTable estoqueTable;
    private javax.swing.JButton excluirProdutoButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
