/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;
import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.bean.Servico;
import model.dao.ServicoDAO;
import javax.swing.JOptionPane; // Para exibir mensagens de diálogo
import model.bean.Estoque;
import model.dao.EstoqueDAO;



/**
 *
 * @author Aluno
 */
public class TelaCadastroEstoques extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaFornecedor
     */
    public TelaCadastroEstoques() {
        initComponents();
        

    }
  public void limpar(){
      // Limpar os campos de entrada
    nomeProdutoField6.setText("");
    quantidadeField6.setText("");
    precoField6.setText("");
  }
    

    
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        quantidadeField6 = new javax.swing.JTextField();
        nomeProdutoField6 = new javax.swing.JTextField();
        cancelarProdutoButton6 = new javax.swing.JButton();
        precoField6 = new javax.swing.JTextField();
        salvarProdutoButton6 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Gerenciamento Clientes");

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro de Estoque", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12), new java.awt.Color(255, 51, 51))); // NOI18N

        jLabel19.setText("Nome do Produto");

        jLabel20.setText("Quantidade ");

        jLabel21.setText("Preço Unitário");

        quantidadeField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantidadeField6ActionPerformed(evt);
            }
        });

        nomeProdutoField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeProdutoField6ActionPerformed(evt);
            }
        });

        cancelarProdutoButton6.setText("Cancelar");
        cancelarProdutoButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarProdutoButton6ActionPerformed(evt);
            }
        });

        precoField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precoField6ActionPerformed(evt);
            }
        });

        salvarProdutoButton6.setText("Salvar ");
        salvarProdutoButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarProdutoButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nomeProdutoField6, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(precoField6, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(quantidadeField6, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(76, 76, 76))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(salvarProdutoButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(cancelarProdutoButton6)
                .addGap(48, 48, 48))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(quantidadeField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(precoField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nomeProdutoField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))))
                .addGap(56, 56, 56)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelarProdutoButton6)
                    .addComponent(salvarProdutoButton6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarProdutoButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarProdutoButton6ActionPerformed
      // Limpar os campos de entrada
    nomeProdutoField6.setText("");
    quantidadeField6.setText("");
    precoField6.setText("");
    }//GEN-LAST:event_cancelarProdutoButton6ActionPerformed

    private void salvarProdutoButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarProdutoButton6ActionPerformed
            // Captura os valores dos campos
       String nomeEstoque = nomeProdutoField6.getText().trim(); // Nome do serviço/produto
       String quantidadeEstoque = quantidadeField6.getText().trim(); // Quantidade ou descrição
       String precoEstoque = precoField6.getText().trim(); // Preço do produto

       // Validação dos campos
       if (nomeEstoque.isEmpty() || quantidadeEstoque.isEmpty() || precoEstoque.isEmpty()) {
           JOptionPane.showMessageDialog(this, "Preencha todos os campos!", "Erro", JOptionPane.ERROR_MESSAGE);
           return;
       }

       try {
           // Converte o preço para Double
           int precoEstoque1 = Integer.parseInt(precoEstoque);
           Double quantidadeEstoque1 = Double.parseDouble(quantidadeEstoque);

           if (precoEstoque1 <= 0) {
               JOptionPane.showMessageDialog(this, "O preço deve ser maior que zero.", "Erro", JOptionPane.ERROR_MESSAGE);
               return;
           }

           // Cria o objeto Estoque com os valores capturados
           Estoque estoqueProduto = new Estoque(nomeEstoque,quantidadeEstoque1, precoEstoque1);

           // Cria a instância do DAO e salva o produto no banco
           EstoqueDAO estoqueDAO = new EstoqueDAO();
           boolean sucesso = estoqueDAO.criarProduto(estoqueProduto);

           if (sucesso) {
               JOptionPane.showMessageDialog(this, "Produto salvo com sucesso no estoque!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
               limpar(); // Método para limpar os campos após o sucesso
           } else {
               JOptionPane.showMessageDialog(this, "Erro ao salvar o produto no banco de dados.", "Erro", JOptionPane.ERROR_MESSAGE);
           }
       } catch (NumberFormatException e) {
           JOptionPane.showMessageDialog(this, "O campo preço deve conter um número válido.", "Erro", JOptionPane.ERROR_MESSAGE);
       }

    }//GEN-LAST:event_salvarProdutoButton6ActionPerformed

    private void nomeProdutoField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeProdutoField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeProdutoField6ActionPerformed

    private void quantidadeField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantidadeField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantidadeField6ActionPerformed

    private void precoField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precoField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precoField6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelarProdutoButton6;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField nomeProdutoField6;
    private javax.swing.JTextField precoField6;
    private javax.swing.JTextField quantidadeField6;
    private javax.swing.JButton salvarProdutoButton6;
    // End of variables declaration//GEN-END:variables
}
