/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.bean.Funcionario;
import model.bean.Servico;
import model.dao.FuncionarioDAO;
import model.dao.ServicoDAO;



/**
 *
 * @author Aluno
 */
public class TelaCadastroServicos extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaFornecedor
     */
    public TelaCadastroServicos() {
        initComponents();

    }
    
     public void limpar() {
        nomeServicoField.setText("");
        descricaoServicoArea.setText("");
    }
    
     
  
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nomeServicoField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        descricaoServicoArea = new javax.swing.JTextArea();
        salvarServicoButton = new javax.swing.JButton();
        cancelarServicoButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        valorServicoField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jcombofuncionario = new javax.swing.JComboBox<>();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Gerenciamento Serviços");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro de Serviço", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 1, 12), new java.awt.Color(51, 0, 0))); // NOI18N

        jLabel1.setText("Tipo de serviço");

        jLabel2.setText("Descrição do Serviço");

        descricaoServicoArea.setColumns(20);
        descricaoServicoArea.setRows(5);
        jScrollPane2.setViewportView(descricaoServicoArea);

        salvarServicoButton.setText("Salvar");
        salvarServicoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarServicoButtonActionPerformed(evt);
            }
        });

        cancelarServicoButton.setText("Cancelar");
        cancelarServicoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarServicoButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Valor");

        jLabel4.setText("Funcionario: ");

        jcombofuncionario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "..." }));
        jcombofuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcombofuncionarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(salvarServicoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(cancelarServicoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcombofuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(nomeServicoField, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(valorServicoField, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeServicoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(valorServicoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcombofuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(salvarServicoButton))
                    .addComponent(cancelarServicoButton)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarServicoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarServicoButtonActionPerformed
        limpar();
    }//GEN-LAST:event_cancelarServicoButtonActionPerformed

    private void salvarServicoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarServicoButtonActionPerformed

    // Captura os valores dos campos
    String nomeServico = nomeServicoField.getText();
    String descricaoServicoText = descricaoServicoArea.getText();
    String precoServicoText = valorServicoField.getText(); // Agora o preço vem de um campo dedicado
    String funcionarioSelecionado = (String) jcombofuncionario.getSelectedItem(); // Captura o nome do funcionário selecionado

    // Validação dos campos
    if (nomeServico.isEmpty() || descricaoServicoText.isEmpty() || precoServicoText.isEmpty() || funcionarioSelecionado == null || funcionarioSelecionado.equals("Selecione um Funcionário")) {
        JOptionPane.showMessageDialog(this, "Preencha todos os campos!", "Erro", JOptionPane.ERROR_MESSAGE);
        return;
    }

    try {
        // Converte o preço para Double
        double precoServico = Double.parseDouble(precoServicoText);

        // Consulta para pegar o ID do funcionário baseado no nome
        int funcionarioId = obterFuncionarioId(funcionarioSelecionado);

        if (funcionarioId == -1) {
            JOptionPane.showMessageDialog(this, "Funcionário não encontrado!", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Cria o objeto Servico com nome, descrição e preço
        Servico servico = new Servico(0, nomeServico, descricaoServicoText, precoServico, funcionarioId);

        // Salva no banco de dados
        ServicoDAO servicoDAO = new ServicoDAO();
        boolean sucesso = servicoDAO.salvar(servico);

        if (sucesso) {
            JOptionPane.showMessageDialog(this, "Serviço salvo com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            limpar(); // Limpa os campos após salvar
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao salvar o serviço.", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "O campo preço deve ser um número válido.", "Erro", JOptionPane.ERROR_MESSAGE);
    }
}

// Método para obter o ID do funcionário baseado no nome selecionado na ComboBox
private int obterFuncionarioId(String nomeFuncionario) {
    int funcionarioId = -1;  // Valor padrão caso o funcionário não seja encontrado

    try (Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/oficina", "root", "")) {
        String sql = "SELECT id FROM funcionarios WHERE nome = ?";
        PreparedStatement stmt = connection.prepareStatement(sql);
        stmt.setString(1, nomeFuncionario);  // Passa o nome do funcionário
        ResultSet rs = stmt.executeQuery();

        if (rs.next()) {
            funcionarioId = rs.getInt("id");
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Erro ao buscar ID do funcionário: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
    }

    return funcionarioId;

    }//GEN-LAST:event_salvarServicoButtonActionPerformed

    private void jcombofuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcombofuncionarioActionPerformed
 try {
     // Consulta SQL para pegar os nomes dos funcionarios
     try ( // Conectar ao banco de dados
             Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/oficina", "root", "")) {
         // Consulta SQL para pegar os nomes dos funcionarios
         String sql = "SELECT id, nome FROM funcionarios";  // Ajuste para sua tabela e coluna
         PreparedStatement stmt = connection.prepareStatement(sql);
         ResultSet rs = stmt.executeQuery();
         // Salvar o índice do cliente selecionado antes de limpar o ComboBox
         int selectedIndex = jcombofuncionario.getSelectedIndex();
         // Limpar o combobox antes de adicionar os novos itens
         jcombofuncionario.removeAllItems();
         // Adicionar clientes ao combobox
         while (rs.next()) {
             String nomeCliente = rs.getString("nome");  // Pegando o nome do funcionario
             jcombofuncionario.addItem(nomeCliente);
         } // Restaurar a seleção do cliente (se possível)
         if (selectedIndex != -1 && selectedIndex < jcombofuncionario.getItemCount()) {
             jcombofuncionario.setSelectedIndex(selectedIndex);
         }
         // Fechar a conexão
     } // Ajuste para sua tabela e coluna

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Erro ao carregar clientes: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jcombofuncionarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelarServicoButton;
    private javax.swing.JTextArea descricaoServicoArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> jcombofuncionario;
    private javax.swing.JTextField nomeServicoField;
    private javax.swing.JButton salvarServicoButton;
    private javax.swing.JTextField valorServicoField;
    // End of variables declaration//GEN-END:variables
}
